services:
  portainer:
    container_name: X05-001-PORTAINER
    image: portainer/portainer-ce:lts
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    ports:
      - 2301:9000
      - 8000:8000

  pihole:
    container_name: X05-002-PIHOLE
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "2302:80/tcp"
    environment:
      TZ: 'America/Managua'
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD}
      FTLCONF_dns_listeningMode: 'ALL'
    volumes:
      - './etc-pihole:/etc/pihole'
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    restart: unless-stopped

  uptime-kuma:
    container_name: X05-003-KUMA
    image: louislam/uptime-kuma:latest
    ports:
      - 2303:3001
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    
  tailscale:
    container_name: X06-004-TAILSCALE
    image: tailscale/tailscale:latest
    restart: always
    volumes:
      - ./tun:/dev/net/tun
      - ./lib:/var/lib
    environment:
      - TS_AUTH_KEY=${TS_KEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ROUTES=172.17.10.0/24
    network_mode: host
    privileged: true
