services:

  pihole:
    container_name: X05-001-PIHOLE
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "2301:80/tcp"
    environment:
      TZ: 'America/Managua'
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD}
      FTLCONF_dns_listeningMode: 'ALL'
    volumes:
      - '/sdata/pihole/etc-pihole:/etc/pihole'
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    restart: unless-stopped

  uptime-kuma:
    container_name: X05-002-KUMA
    image: louislam/uptime-kuma:latest
    ports:
      - 2302:3001
    volumes:
      - /sdata/kuma/data:/app/data
    restart: unless-stopped
  
  tailscale:
    image: tailscale/tailscale:latest
    container_name: X05-003-TAILSCALE
    hostname: X05-AJAX
    environment:
      - TS_AUTHKEY=${TS_KEY}
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - /sdata/tailscale-state:/var/lib/tailscale
    cap_add:
      - net_admin
      - net_raw
    restart: unless-stopped
